export enum EMSSysSpecName {
	HYBRID_MODE_SUPPORTED = 'hybridModeSupported',
	INSTALLED_BATTERY_CAPACITY = 'installedBatteryCapacity',
	MAX_AC_POWER = 'maxAcPower',
	MAX_BATTERY_CHARGE_POWER = 'maxBatChargePower',
	MAX_BATTERY_DISCHARGE_POWER = 'maxBatDischargPower',
	MAX_CHARGE_POWER = 'maxChargePower',
	MAX_DISCHARGE_POWER = 'maxDischargePower',
	MAX_FBC_CHARGE_POWER = 'maxFbcChargePower',
	MAX_FBC_DISCHARGE_POWER = 'maxFbcDischargePower',
	MAX_PV_POWER = 'maxPvPower',
	MAX_START_CHARGE_POWER = 'maxStartChargePower',
	MAX_START_DISCHARGE_POWER = 'maxStartDischargePower',
	MIN_START_CHARGE_POWER = 'minStartChargePower',
	MIN_START_DISCHARGE_POWER = 'minStartDischargePower',
	RECOMMENDED_MIN_CHARGE_LIMIT = 'recommendedMinChargeLimit',
	RECOMMENDED_MIN_DISCHARGE_LIMIT = 'recommendedMinDischargeLimit',
	START_CHARGE_DEFAULT = 'startChargeDefault',
	START_DISCHARGE_DEFAULT = 'startDischargeDefault',
}
